# Generated by Django 5.1.1 on 2025-05-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cat')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cho')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='dec')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='djs')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gif')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ven')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='inv')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='jew')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mak')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mehendi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='meh')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pho')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='wea')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.catering')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_cho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.choreographer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_dec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.decorator')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_djs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.dj')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.gift')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_ven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_inv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_jew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.jewellery')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_mak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.makeup')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_meh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.mehendi')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_pho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.photographer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_wea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=50)),
                ('Gmail_Address', models.CharField(max_length=50)),
                ('Function_Date', models.DateField()),
                ('date_on', models.DateField(auto_now=True)),
                ('Event_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.wear')),
            ],
        ),
    ]
